title: My Blog 
description: This is my personal blog and you can find some interesting things here. 
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
  - jekyll-remote-theme 

# paginate: 5 
# paginate_path: "/page:num/" 

# show_excerpts: true 